### ISSUE TITLE
Missing req for installation

### ISSUE THREAD

**Issue by dakotalightning** [getgrav/grav-skeleton-agency-site#2]
It appears this package is missing the grav core and admin for this to work

**Comment by rhukster** [comment]
The skeleton repo is just the `user/` folder plus a `.dependencies` file.  We have a builder script that builds out the full package and this is automatically and uploads it to the releases for downloads.

**Comment by dakotalightning** [comment]
Little confused since the `readme.md` sates

> 1. Download HPSTR Skeleton
> 2. Simply unzip the package into your web root folder.
> 3. Point your browser at the folder, job done!

It doesn't work. When the others include everything you need to get going.

> skeleton is an all-in-one package

An I missing something?
