### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gxjansen** [getgrav/grav-skeleton-agency-site#3]
When I upload this and go to the homepage I get an error:

Server Error
Sorry, something went terribly wrong!

0 - An exception has been thrown during the rendering of a template ("Template "modular/contact.html.twig" is not defined.") in "modular.html.twig" at line 10.

**Comment by flaviocopes** [comment]
Recreated, on it

**Comment by flaviocopes** [comment]
Fixed by releasing a skeleton update https://github.com/getgrav/grav-skeleton-agency-site/releases/tag/1.0.3

**Comment by flaviocopes** [comment]
Was already fixed in the develop branch, but missed a new release to be up in the released version
