### ISSUE TITLE
Simple_form Feedback message

### ISSUE THREAD

**Issue by haviana** [getgrav/grav-skeleton-agency-site#4]
Hi there,

I am using your template, and already have the simple_form working. Meaning that, i already get emails from the contact form. Nonetheless, i am having troubles with the feedback message. The following is describes what i have done:
1. Workaround 
   Create a folder with name thankyou
   Create a standard file with .md, which contains the returned messages.
   Set the redirect_to to thankyou folder. 
2. Workaround 
   Tried to set the message after the process tag in the file contact.md 

None of them worked. Could you please help me?

The code is available at https://github.com/haviana/Boavida.

Thank you in advance.

**Comment by flaviocopes** [comment]
The simple_form plugin has been discontinued (and removed) by its developer. Use the (core Grav) Form plugin instead. Check https://learn.getgrav.org/forms/forms/example-form as an example of a contact form.
