### ISSUE TITLE
Menu Control

### ISSUE THREAD

**Issue by elproducto** [getgrav/grav-skeleton-agency-site#7]
I would like to remove the About us section & Menu item for my use case.  It seem even after disabling the Visibility and Publishing for the About Us page, the  About Us menu item shows up at the top of the page.  What should be done to ensure the About Us menu item no longer shows?

**Comment by flaviocopes** [comment]
You probably need to remove them from https://github.com/getgrav/grav-skeleton-agency-site/blob/develop/config/site.yaml too. And clear/disable the pages cache

**Comment by elproducto** [comment]
Thanks.  I did not dump the whole skeleton into my HTML root folder.  I am testing this theme using multisite by just copying the config, pages, plugins and theme folder into a subdirectory.  You response lead me in the right direction, but I had to look for "#about" using grep.  Look like it was located in config/site.yaml in relation to the subdirectory used.
